### ISSUE TITLE
Explorer context

### ISSUE THREAD

**Issue by rlnt** [takkaO/VSCode-OpenWindowTabContext#10]
It would be nice if the `Open in new window` action would also be existing in the explorer context.
Currently, you can only open files in new windows if you opened them.

This would be handy because you could just right-click any file from your explorer tree to open it in a new window.
There is another extension that does this. I had to combine yours with it to have both options.

I also requested the tab context action on their repository but it wasn't updated since 2020 so I try it here.
https://github.com/onatm/open-in-new-window

**Comment by takkaO** [comment]
**Thank you for using this extension ! 😉**

At the moment, I am reluctant to take this issue.
There are two reasons.
The first is that it seems to be able to achieve the required functionality by combining it with onatm's extension.
The second reason is that onatm's extension has no bugs or security issues (or so it seems).

If Mr. onatm's extension has some problems or security holes and they are not addressed, I am willing to add the function to OpenWindowTabContext.

**Comment by rlnt** [comment]
The reason I am requesting this is to remove one extension. VSCode gets more and more bloated because of different extensions that only add one feature. Installing additional extensions which only add a compatibility feature to an already existing feature just seems unnecessary.
I don't think this suggestion is out of the scope of your extension since it's a nice QoL feature and would really save some time.
Adding the functionality of your extension was also considered here: https://github.com/onatm/open-in-new-window/issues/3

**Comment by takkaO** [comment]
>VSCode gets more and more bloated because of different extensions that only add one feature.

I understand your feelings to some degree.

I will try to develop the features suggested in this issue.
However, we will carefully consider whether or not to merge them in the end.

**Comment by takkaO** [comment]
I have implemented this feature on a trial basis since version 1.7.0.
Please enable the feature in your settings and give us feedback on this feature.

**Comment by rlnt** [comment]
Works very well. I was able to instantly uninstall the other extension. Thanks a lot!
