### ISSUE TITLE
[Question] Remove features to override Open File

### ISSUE THREAD

**Issue by lonix1** [takkaO/VSCode-OpenWindowTabContext#14]
The latest version says this:
> Remove features to override "Open File" menu to open in a new window (1.8.0) because already implemented as Microsoft.

I'm using the latest version of vscode, and there is no option to open a new window (that I can find). Where do I look?

So this extension is still very useful!

**Comment by takkaO** [comment]
Please search```window.openFilesInNewWindow``` on VSCode settings and set ```on```.

![キャプチャ](https://user-images.githubusercontent.com/46308252/166103103-98e7e6dc-3dbf-47ca-be3d-d7b69cfd3f9c.PNG)
