### ISSUE TITLE
Not working with VSCode-Insiders (launched from WSL2)

### ISSUE THREAD

**Issue by Unintendedz** [takkaO/VSCode-OpenWindowTabContext#15]
When using this extension with VSCode - Insiders (launched from WSL2), I got this error notification
![image](https://user-images.githubusercontent.com/64687143/172798266-899ae76e-0dc8-451d-a97b-59854065f8d4.png)

Then I've tried to change `Command to open new window.` option from default value `code` to `code-insiders`, the error notification is gone but still can't open new window from tab. 

I don't know if I miss anything, or if this behavior is intended. 

Thank you for making this great extension.

**Comment by takkaO** [comment]
**Thank you for using this extension 😉**

Please tell me more about the **launched from WSL2** method.
Is the following image correct?
````powershell
# In Powershell
$> bash            # launch linux (WSL)
linux$> code .     # launch vscode
```` 
And how to install VSCode into WSL2?

Thank you.

**Comment by Unintendedz** [comment]
Yes, your image is correct. But you need to install "Remote - WSL" extension first.

take a look at [this link](https://code.visualstudio.com/docs/remote/wsl-tutorial) if you want more detail.

**Comment by takkaO** [comment]
Sorry it is taking so long 🙇. My private is busy now.

I could not reproduce this on the stable version of VSCode.
I would like to try it with the insider version. 
Can you tell me how to build the environment and reproduce the problem, including how to install it?

**Comment by takkaO** [comment]
I could not reproduce issue on the insider version of VSCode too.

In my environment, I changed ```Command``` in the settings to ```code-insiders``` and it worked fine. It also works when booting from WSL2.

![ss](https://user-images.githubusercontent.com/46308252/175034811-4c89b6f1-7627-4927-9604-06d1067182a6.png)

**Comment by Unintendedz** [comment]
Hi there, sorry for the late reply. 

After seeing your response, I realized I installed the Insiders version using the Scoop package manager when I opened this issue.  🤷🏻

The official Insiders version installer is okay with your extension; that's true, and I've just tested too. 

If you're not interested in figuring out why Scoop installation would cause this problem (or maybe just in my environment, I don't have a second machine to test this), I say we should close this issue.

I'm switching to the Stable version now, but I appreciate your efforts. Thanks.

**Comment by takkaO** [comment]
I tried to install by scoop package manager on a virtual machine but could not reproduce the issue (```code``` -> ```code-insiders``` change is required ).
If a more detailed reproduction procedure can be provided, we would like to respond.

Thank you.
