### ISSUE TITLE
Consider Publishing to Registry used by VSCodium

### ISSUE THREAD

**Issue by IronFractal** [takkaO/VSCode-OpenWindowTabContext#18]
Could you publish the extension to https://open-vsx.org/ ?

This is the registry/marketplace used by VSCodium. VSCodium does not use the Microsoft Marketplace by default thus this extension does not appear to VSCodium users and requires manual installation via VSIX file.

**Comment by takkaO** [comment]
Thank you. This is the first time I knew about it 😲.
I hope to publish it to https://open-vsx.org/ soon.

I will report here when I release done.
